### ISSUE TITLE
Add check scripts for TypeScript module resolution

### ISSUE THREAD

**Issue by azu** [textlint/textlint#440]
This issue is based on  #414

## Issue

This issue exist in TypeScript `paths` mapping and monorepo.

#413 Cause unexpected "Cannot find module" error.

```
 ../@textlint/kernel/src/core/BaseRuleContext.ts(1,39): error TS2307: Cannot find module '@textlint/ast-node-types'.
lerna ERR! ../@textlint/kernel/src/core/filter-rule-context.ts(4,25): error TS2307: Cannot find module '@textlint/ast-node-types'.
```

This error is caused by build dependency in this monorepo.

>`textlint-formatter` -> depend on -> `@textlint/kernel` -> depend on -> `@textlint/ast-node-types`

When building `textlint-formatter`, `@textlint/kernel`'s `lib/` is not built yet.
It cause reference error like "TS2307: Cannot find module"

But, we have already `path` mapping for avoiding this error.
It make `textlint-formatter` refer to `src/`  instead of `lib/`.
https://github.com/textlint/textlint/blob/37bccdb9a91382c00deb914e4e7195eba9700a94/tsconfig.base.json#L4-L11

- [Module Resolution · TypeScript](https://www.typescriptlang.org/docs/handbook/module-resolution.html "Module Resolution · TypeScript")
- [Quramy/lerna-yarn-workspaces-example: How to build TypeScript mono-repo project with yarn and lerna](https://github.com/Quramy/lerna-yarn-workspaces-example "Quramy/lerna-yarn-workspaces-example: How to build TypeScript mono-repo project with yarn and lerna")

The `paths` mapping is following([tsconfig.base.json](https://github.com/textlint/textlint/blob/master/tsconfig.base.json "tsconfig.base.json")):

```ts
    "baseUrl": ".",
    "paths": {
      "@textlint/*": [
        "./packages/@textlint/*/src"
      ],
      "*": [
        "./packages/*/src"
      ]
    },
```

This `paths` mapping means that `@textlint/ast-node-types` is treated as `packages/@textlint/ast-node-types/src`

```js
require("@textlint/ast-node-types")
// `paths` map to =>
require("packages/@textlint/ast-node-types/src")
```

This is **incompleteness**.

Because, `require("packages/@textlint/ast-node-types/src")` refer to `require("packages/@textlint/ast-node-types/src/index.ts")`.
But,  `packages/@textlint/ast-node-types/src/index.ts` is not found.
As as result, `require("@textlint/ast-node-types")` can not resoluve `paths`.

It throw error

>  ../@textlint/kernel/src/core/BaseRuleContext.ts(1,39): error TS2307: Cannot find module '@textlint/ast-node-types'.

## Workarount for Issue

We have used a workaround for this issue.
This is introduced in #414 

- Always put `src/index.ts`
  - It can be resolved by `require("packages/@textlint/hoge/src")`
- Each `tsconfig.json` extends [tsconfig.base.json](https://github.com/textlint/textlint/blob/master/tsconfig.base.json "tsconfig.base.json")

## ☑️  Tasks 

We need to get more stability.
So, we can add check script for this convention(workaround).

- [ ] Add check script for checking `src/index.ts`
- [ ] Add check script for checking `tsconfig.json

## 🙇 Help wanted 

If you know correct solution, please let us.

**Comment by azu** [comment]
Related TypeScript issue: [Support "medium-sized" projects · Issue #3469 · Microsoft/TypeScript](https://github.com/Microsoft/TypeScript/issues/3469 "Support &#34;medium-sized&#34; projects · Issue #3469 · Microsoft/TypeScript")

**Comment by 0x6b** [comment]
Note to future self: Reading [TypeScript Module Resolution document](https://www.typescriptlang.org/docs/handbook/module-resolution.html#virtual-directories-with-rootdirs) and it looks difficult to solve this issue.

Not so pretty but just for quick check:

```sh
$ yarn lerna exec --concurrency 1 "echo \$LERNA_PACKAGE_NAME; jq .main,.types,.devDependencies.typescript package.json"
```

Found that we have to rename main script to `index.ts` when converting following packages to TypeScript:

- [`@textlint/ast-tester/package.json`](https://github.com/textlint/textlint/blob/9f6d22e7cdcf769301b51d66fa0e5aa9318994df/packages/%40textlint/ast-tester/package.json)
- [`@textlint/feature-flag/package.json`](https://github.com/textlint/textlint/blob/9f6d22e7cdcf769301b51d66fa0e5aa9318994df/packages/%40textlint/feature-flag/package.json)
- [`@textlint/markdown-to-ast/package.json`](https://github.com/textlint/textlint/blob/9f6d22e7cdcf769301b51d66fa0e5aa9318994df/packages/%40textlint/markdown-to-ast/package.json)

Also found that [`@textlint/kernel/package.json`](https://github.com/textlint/textlint/blob/9f6d22e7cdcf769301b51d66fa0e5aa9318994df/packages/%40textlint/kernel/package.json) uses `typings` instead of `types`.
